USE [master];
GO

IF EXISTS (SELECT name FROM sys.databases WHERE name = 'LMS')
BEGIN
  ALTER DATABASE [LMS] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
  DROP DATABASE [LMS];
END
GO

CREATE DATABASE [LMS] CONTAINMENT = NONE
GO
